### ISSUE TITLE
How to remove scrollbar?

### ISSUE THREAD

**Issue by decafboba** [richardscarrott/react-snap-carousel#21]
In some of the examples (e.g. https://richardscarrott.github.io/react-snap-carousel/?path=/story/slideshow--scroll-padding) it appears the horizontal scrollbar is gone.

How is this accomplished?

**Comment by richardscarrott** [comment]
@0xTenzo you can hide it with CSS, see here https://github.com/richardscarrott/react-snap-carousel/blob/c1e5395c23afd071ba66cc89d8ae956c00210a51/stories/carousel.module.css#L20-L28

```css
/* Hide scrollbar for Chrome, Safari and Opera */
.example::-webkit-scrollbar {
  display: none;
}

/* Hide scrollbar for IE, Edge and Firefox */
.example {
  -ms-overflow-style: none;  /* IE and Edge */
  scrollbar-width: none;  /* Firefox */
}
```
