### ISSUE TITLE
Support scroll padding

### ISSUE THREAD

**Issue by richardscarrott** [richardscarrott/react-snap-carousel#3]
Currently scroll padding isn't factored in when computing the `pages`.

Some common scenarios include:

Scenario 1:
```css
.scroll {
  scroll-padding: 0 100px;
}
```

Scenario 2:
```css
.scroll {
  scroll-padding: 0 100px;
  padding: 0 100px; /* Allows the scroll-padding to take effect on the first item */
}
```

Also need to handle scroll-margin which is declared on an item & I think is calculated in addition to scroll padding.
